-- MySQL Script generated by MySQL Workbench
-- Thu Sep  8 10:50:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RAMAKA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RAMAKA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RAMAKA` DEFAULT CHARACTER SET utf8 ;
USE `RAMAKA` ;

-- -----------------------------------------------------
-- Table `RAMAKA`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RAMAKA`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(255) NOT NULL,
  `p_apellido` VARCHAR(50) NOT NULL,
  `s_apellido` VARCHAR(45) NOT NULL,
  `telefono` DOUBLE NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(255) NOT NULL,
  `referencias` VARCHAR(255) NOT NULL,
  `ciudad` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `CP` INT NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RAMAKA`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RAMAKA`.`pedidos` (
  `id_pedidos` INT NOT NULL AUTO_INCREMENT,
  `estatus` VARCHAR(45) NOT NULL,
  `numero_rastreo` VARCHAR(50) NOT NULL,
  `fecha_pedido` DATE NOT NULL,
  `notas` VARCHAR(255) NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_pedidos`, `cliente_id_cliente`),
  INDEX `fk_pedidos_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `RAMAKA`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RAMAKA`.`cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RAMAKA`.`cotizacion` (
  `id_cotizacion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `descripcion_cotizacion` VARCHAR(255) NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_cotizacion`, `cliente_id_cliente`),
  INDEX `fk_cotizacion_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_cotizacion_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `RAMAKA`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RAMAKA`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RAMAKA`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `descripcion_producto` VARCHAR(255) NOT NULL,
  `precio_producto` FLOAT NOT NULL,
  `cantidad_producto` INT NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RAMAKA`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RAMAKA`.`registro` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `cliente_id_cliente`),
  INDEX `fk_registro_cliente_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_registro_cliente`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `RAMAKA`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RAMAKA`.`producto_has_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RAMAKA`.`producto_has_pedidos` (
  `producto_id_producto` INT NOT NULL,
  `pedidos_id_pedidos` INT NOT NULL,
  `pedidos_cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`producto_id_producto`, `pedidos_id_pedidos`, `pedidos_cliente_id_cliente`),
  INDEX `fk_producto_has_pedidos_pedidos1_idx` (`pedidos_id_pedidos` ASC, `pedidos_cliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_producto_has_pedidos_producto1_idx` (`producto_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_producto_has_pedidos_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `RAMAKA`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_pedidos_pedidos1`
    FOREIGN KEY (`pedidos_id_pedidos` , `pedidos_cliente_id_cliente`)
    REFERENCES `RAMAKA`.`pedidos` (`id_pedidos` , `cliente_id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
